name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
        
    - name: Install dependencies
      run: |
        sudo apt-get update -y
        sudo apt-get install zfsutils-linux -y
        whereis zfs
        whereis zpool

    - name: Initialize with zpool
      run: |
        sudo dd if=/dev/zero of=loopbackfile.img bs=10M count=10
        du -sh
        sudo losetup -fP loopbackfile.img
        sudo losetup -a
        sudo zpool create tank /dev/loop0
    
    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
