# .github/workflows/release.yaml
# https://github.com/marketplace/actions/go-release-binaries

on: 
  release:
    types: [created]

jobs:
  release-linux-amd64:
    name: release linux/amd64
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: wangyoucao577/go-release-action@v1.18
      with:
        github_token: ${{ secrets.UPLOAD_TOKEN }}
        goos: linux
        goarch: amd64